# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_widget(object):
    def setupUi(self, show_widget):
        show_widget.setObjectName("show_widget")
        show_widget.resize(900, 600)
        self.show_widget_number = show_widget.winId()
        self.retranslateUi(show_widget)
        QtCore.QMetaObject.connectSlotsByName(show_widget)

    def retranslateUi(self, show_widget):
        _translate = QtCore.QCoreApplication.translate
        show_widget.setWindowTitle(_translate("show_widget", "Form"))
