# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Up.setGeometry(QtCore.QRect(560, 670, 78, 23))
        self.pushButton_Up.setObjectName("pushButton_Up")
        self.pushButton_Left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Left.setGeometry(QtCore.QRect(660, 670, 78, 23))
        self.pushButton_Left.setObjectName("pushButton_Left")
        self.pushButton_Down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Down.setGeometry(QtCore.QRect(560, 700, 78, 23))
        self.pushButton_Down.setObjectName("pushButton_Down")
        self.pushButton_Right = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Right.setGeometry(QtCore.QRect(660, 700, 78, 23))
        self.pushButton_Right.setObjectName("pushButton_Right")
        self.pushButton_ZoomIn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZoomIn.setGeometry(QtCore.QRect(560, 730, 78, 23))
        self.pushButton_ZoomIn.setObjectName("pushButton_ZoomIn")
        self.pushButton_ZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZoomOut.setGeometry(QtCore.QRect(660, 730, 78, 23))
        self.pushButton_ZoomOut.setObjectName("pushButton_ZoomOut")
        self.graph_view = QtWidgets.QLabel(self.centralwidget)
        self.graph_view.setGeometry(QtCore.QRect(730, 30, 640, 360))
        self.graph_view.setText("")
        self.graph_view.setObjectName("graph_view")
        self.pushButton_screenshot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_screenshot.setGeometry(QtCore.QRect(560, 630, 78, 23))
        self.pushButton_screenshot.setObjectName("pushButton_screenshot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 590, 101, 31))
        self.label.setObjectName("label")
        self.graph_view_2 = QtWidgets.QLabel(self.centralwidget)
        self.graph_view_2.setGeometry(QtCore.QRect(40, 30, 640, 360))
        self.graph_view_2.setText("")
        self.graph_view_2.setObjectName("graph_view_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 480, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1060, 490, 111, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Up.setText(_translate("MainWindow", "向上"))
        self.pushButton_Left.setText(_translate("MainWindow", "向左"))
        self.pushButton_Down.setText(_translate("MainWindow", "向下"))
        self.pushButton_Right.setText(_translate("MainWindow", "向右"))
        self.pushButton_ZoomIn.setText(_translate("MainWindow", "变焦变大"))
        self.pushButton_ZoomOut.setText(_translate("MainWindow", "变焦变小"))
        self.pushButton_screenshot.setText(_translate("MainWindow", "截图"))
        self.label.setText(_translate("MainWindow", "基本功能"))
        self.label_4.setText(_translate("MainWindow", "RTSP画面"))
        self.label_5.setText(_translate("MainWindow", "捕获画面"))
